services:
  mighty:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ""
      REDIS_DB: ""
    secrets:
      - postgres_password
    depends_on:
      - redis
      - postgres   # Mighty will start after Redis and Postgres containers start
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5432:5432"

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt